// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodef/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignInRequest struct {
	MasterPassword       int32    `protobuf:"varint,1,opt,name=master_password,json=masterPassword,proto3" json:"master_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetMasterPassword() int32 {
	if m != nil {
		return m.MasterPassword
	}
	return 0
}

type SignInResponse struct {
	ClientToken          string   `protobuf:"bytes,1,opt,name=client_token,json=clientToken,proto3" json:"client_token,omitempty"`
	AliveUntil           int32    `protobuf:"varint,2,opt,name=alive_until,json=aliveUntil,proto3" json:"alive_until,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

func (m *SignInResponse) GetAliveUntil() int32 {
	if m != nil {
		return m.AliveUntil
	}
	return 0
}

type SignOutRequest struct {
	ClientToken          int32    `protobuf:"varint,1,opt,name=client_token,json=clientToken,proto3" json:"client_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{2}
}

func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

func (m *SignOutRequest) GetClientToken() int32 {
	if m != nil {
		return m.ClientToken
	}
	return 0
}

type SignOutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{3}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

type KeepAliveRequest struct {
	ClientToken          int32    `protobuf:"varint,1,opt,name=client_token,json=clientToken,proto3" json:"client_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{4}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetClientToken() int32 {
	if m != nil {
		return m.ClientToken
	}
	return 0
}

type KeepAliveResponse struct {
	AliveUntil           int32    `protobuf:"varint,1,opt,name=alive_until,json=aliveUntil,proto3" json:"alive_until,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_197eef2df98d5967, []int{5}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

func (m *KeepAliveResponse) GetAliveUntil() int32 {
	if m != nil {
		return m.AliveUntil
	}
	return 0
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "auth.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "auth.SignInResponse")
	proto.RegisterType((*SignOutRequest)(nil), "auth.SignOutRequest")
	proto.RegisterType((*SignOutResponse)(nil), "auth.SignOutResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "auth.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "auth.KeepAliveResponse")
}

func init() { proto.RegisterFile("protodef/auth.proto", fileDescriptor_197eef2df98d5967) }

var fileDescriptor_197eef2df98d5967 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0xfd, 0x06, 0x30, 0x0c, 0x0a, 0xb2, 0xf8, 0x83, 0x70, 0x51, 0x7b, 0xd1, 0x8b,
	0x6c, 0x22, 0x92, 0x70, 0x32, 0x81, 0x78, 0x31, 0x1e, 0x34, 0x80, 0x17, 0x2f, 0xa4, 0x94, 0x91,
	0x6e, 0x28, 0xbb, 0x6b, 0x77, 0x8a, 0x7f, 0x9a, 0xff, 0x9e, 0xe9, 0xb6, 0x20, 0x54, 0x2f, 0xde,
	0x76, 0x3f, 0x99, 0xf7, 0xf2, 0xe6, 0x65, 0xa0, 0xa1, 0x23, 0x45, 0x6a, 0x86, 0x6f, 0xdc, 0x8b,
	0x29, 0x68, 0xdb, 0x1f, 0x2b, 0x24, 0x6f, 0xb7, 0x07, 0x07, 0x23, 0x31, 0x97, 0x0f, 0x72, 0x88,
	0xef, 0x31, 0x1a, 0x62, 0x97, 0x50, 0x5b, 0x7a, 0x86, 0x30, 0x9a, 0x68, 0xcf, 0x98, 0x0f, 0x15,
	0xcd, 0x9a, 0xce, 0xb9, 0x73, 0x55, 0x1c, 0x56, 0x53, 0xfc, 0x9c, 0x51, 0x77, 0x0c, 0xd5, 0xb5,
	0xd2, 0x68, 0x25, 0x0d, 0xb2, 0x0b, 0xd8, 0xf7, 0x43, 0x81, 0x92, 0x26, 0xa4, 0x16, 0x28, 0xad,
	0xae, 0x3c, 0xac, 0xa4, 0x6c, 0x9c, 0x20, 0x76, 0x06, 0x15, 0x2f, 0x14, 0x2b, 0x9c, 0xc4, 0x92,
	0x44, 0xd8, 0xfc, 0x6f, 0x9d, 0xc1, 0xa2, 0x97, 0x84, 0xb8, 0x9d, 0xd4, 0xf5, 0x29, 0xa6, 0x75,
	0xa0, 0xdf, 0x5c, 0x8b, 0x3b, 0xae, 0x6e, 0x1d, 0x6a, 0x1b, 0x51, 0x9a, 0xc5, 0xed, 0xc2, 0xe1,
	0x23, 0xa2, 0xee, 0x27, 0xce, 0x7f, 0x70, 0xba, 0x85, 0xfa, 0x96, 0x2c, 0xdb, 0x2b, 0x17, 0xda,
	0xc9, 0x87, 0xbe, 0xf9, 0x74, 0xa0, 0xd0, 0x8f, 0x29, 0x60, 0x5d, 0x28, 0xa5, 0x9d, 0xb0, 0x46,
	0xdb, 0x56, 0xbd, 0xd3, 0x6d, 0xeb, 0x68, 0x17, 0x66, 0x51, 0xff, 0xb1, 0x1e, 0xec, 0x65, 0xf9,
	0xd9, 0xd6, 0xc8, 0x77, 0x07, 0xad, 0xe3, 0x1c, 0xdd, 0x28, 0xef, 0xa0, 0xbc, 0xc9, 0xcb, 0x4e,
	0xd2, 0xa9, 0xfc, 0xde, 0xad, 0xd3, 0x1f, 0x7c, 0xad, 0x1f, 0xdc, 0xbf, 0x0e, 0xe6, 0x82, 0x82,
	0x78, 0xda, 0xf6, 0xd5, 0x92, 0x8f, 0x50, 0x48, 0x4f, 0x6b, 0x6e, 0x50, 0x48, 0x6e, 0xc8, 0x9b,
	0x86, 0xc8, 0xe7, 0x8a, 0xcf, 0xd0, 0x2c, 0x48, 0xe9, 0xeb, 0x00, 0x43, 0x8d, 0x11, 0x37, 0x91,
	0xcf, 0x0d, 0x46, 0x2b, 0xe1, 0xa3, 0xb1, 0x07, 0x35, 0x2d, 0xd9, 0x8b, 0xea, 0x7c, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x38, 0x37, 0x8e, 0x4c, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error) {
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error)
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Auth_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Auth_SignOut_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _Auth_KeepAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protodef/auth.proto",
}
